project_id = "dteppsfseusqixuppglh"

[auth.password]
enable_leaked_password_protection = true
min_length = 8
required_characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

[functions.webhook-conversas]
verify_jwt = false

[functions.api-funil-vendas]
verify_jwt = true

[functions.api-tarefas]
verify_jwt = true

[functions.enviar-whatsapp]
verify_jwt = true

[functions.transcrever-audio]
verify_jwt = true
